// Generated by SolidPython 1.1.3 on 2024-12-04 15:32:43
$fn = 90;


difference() {
	scale(v = [1.5000000000, 1, 1]) {
		cylinder(h = 1.5000000000, r = 0.5000000000);
	}
	scale(v = [1.6000000000, 1.1000000000, 1]) {
		cylinder(h = 2, r = 0.4000000000);
	}
	scale(v = [2, 0.2000000000, 2]) {
		translate(v = [-0.5000000000, -0.5000000000, 0]) {
			cube();
		}
	}
	translate(v = [0, 0.7000000000, 0.5000000000]) {
		rotate(a = [90, 0, 0]) {
			cylinder(h = 2, r = 0.4500000000);
		}
	}
	rotate(a = [0, 15, 0]) {
		translate(v = [-1.4000000000, -0.8000000000, 1]) {
			cube(size = 2);
		}
	}
	difference() {
		translate(v = [-1.6500000000, -0.8000000000, 0.7000000000]) {
			cube(size = 1.5000000000);
		}
		translate(v = [-0.2500000000, 0.7000000000, 0.5900000000]) {
			rotate(a = [90, 0, 0]) {
				cylinder(h = 2, r = 0.5000000000);
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# SolidPython example code 
# Brygg Ullmer, Clemson University
# Begun 2024-10-24
# Documented on 2024-12-04

from solid import *        # load in SolidPython/SCAD support code

cyl1a = cylinder(r=.5,  h=1.5); cyl1b = scale([1.5, 1,   1])(cyl1a) #cyl1b expresses the outer perimeter.  
cyl2a = cylinder(r=.4,  h=2);   cyl2b = scale([1.6, 1.1, 1])(cyl2a) #cyl2b is for cutting away the inside
outGeom = cyl1b - cyl2b #output as exSolid04a.png. this performs the subtraction/cut, leaving an elliptical pipe.  

cube1a = cube();  cube1b = translate([ -.5, -.5, 0 ])(cube1a); cube1c = scale([2, .2, 2])(cube1b) #for cutting the pipe in two
cyl3a  = cylinder(r=.45, h=2); cyl3b = rotate(a = [90, 0, 0])(cyl3a)
cyl3c  = translate([0, .7, .5 ])(cyl3b) #cylinder for large hole perforating the two halves of the oculus

outGeom -= cube1c #cleave the pipe into left and right halves
outGeom -= cyl3c  #output as exSolid04b.png. perforate the two halves of the oculus 

trimTopHeight = 1; trimTopAngle = 15 #15 degree angle to trimming of top of oculus

cube2a = cube(2);   cube2b = translate([-1.4, -.8, trimTopHeight])(cube2a)
cube2c = rotate(a = [0, trimTopAngle, 0])(cube2b)
cube3a = cube(1.5); cube3b = translate([-1.65,-.8, .7])(cube3a)
cyl4a  = cylinder(r=.5,  h=2); cyl4b = rotate(a = [90, 0, 0])(cyl4a); cyl4c  = translate([-.25,  .7, .59])(cyl4b)

outGeom -= cube2c #cube2c trims the top of the two oculus halves (at height trimTopHeight, angle trimTopAngle)
roundOutTopEdge = cube3b - cyl4c # SolidPython doesn't presently provide a bevel/fillet, but we can approximate
outGeom -= roundOutTopEdge

radialSegments = 90; hdr = '$fn = %s;' % radialSegments # create a header for the export
scad_render_to_file(outGeom, 'exSolid04c.scad', file_header=hdr) # write the .scad file

### end ###

 
 
************************************************/
