# Enodia prism intersects 
# Brygg Ullmer, Clemson University
# Begun 2025-11-17

import math
import pygame
import pygame.gfxdraw
import pyclipper

from typing  import List, Tuple
from ataBase import *

CoordF = Tuple[float, float]
CoordI = Tuple[int, int]

class EnoPrismIntersects(AtaBase):
  winWidth, winHeight = None, None
  barHeight           = 10 

  ############# constructor #############

  def __init__(self, **kwargs):
    self.__dict__.update(kwargs) #allow class fields to be passed in constructor

  ############# generate horiz bar coords #############

  def genHorizBarCoords(self, vertPos: int) -> List[CoordI]:
    a, b = (0, vertPos), (self.winWidth, vertPos)
    c    = (self.winWidth, vertPos + self.barHeight)
    d    = (0,             vertPos + self.barHeight)
    return [a,b,c,d]

  ############# intersect quad polys integer #############

  def intersectQuadPolysI(self, quadPolyA: List[CoordI], quadPolyB: List[CoordI]) -> List[CoordI]:
      """
      Compute intersection of two quadrilateral polygons via pyclipper/Clipper (integer kernel).
      Returns a single boundary list [(x,y), ...] if a polygonal area exists; otherwise [].
  
      Notes:
      - Uses NonZero fill rule (typical for general polygons). For simple quads it matches EvenOdd.
      - Generated by copilot in dialog with BAU
      """
  
      # Clipper expects closed paths, but pyclipper accepts them as simple lists; it closes internally.
      subj = quadPolyA
      clip = quadPolyB
  
      pc = pyclipper.Pyclipper()
      #pc.AddPaths(subj, pyclipper.PT_SUBJECT, closed=True)
      #pc.AddPaths(clip, pyclipter.PT_CLIP, closed=True)  # <-- typo fixed below
      pc.AddPath(subj, pyclipper.PT_SUBJECT, closed=True)
      pc.AddPath(clip, pyclipper.PT_CLIP,    closed=True)

      # Execute the intersection. For convex quads this will be 0 or 1 path most of the time.
      solution = pc.Execute(pyclipper.CT_INTERSECTION, pyclipper.PFT_NONZERO, pyclipper.PFT_NONZERO)
  
      if not solution: return []
  
      # If multiple rings are returned, pick the one with the largest area (safe for convex quads).
      # Clipper's Area returns signed area in the same integer units.
      best = max(solution, key=lambda path: abs(pyclipper.Area(path)))
      return best
  
### end ###
