grep -ic hydrogen osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/hydrogen
grep -ic helium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/helium
grep -ic lithium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/lithium
grep -ic beryllium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/beryllium
grep -ic boron osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/boron
grep -ic carbon osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/carbon
grep -ic nitrogen osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/nitrogen
grep -ic oxygen osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/oxygen
grep -ic fluorine osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/fluorine
grep -ic neon osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/neon
grep -ic sodium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/sodium
grep -ic magnesium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/magnesium
grep -ic aluminium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/aluminium
grep -ic silicon osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/silicon
grep -ic phosphorus osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/phosphorus
grep -ic sulfur osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/sulfur
grep -ic chlorine osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/chlorine
grep -ic argon osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/argon
grep -ic potassium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/potassium
grep -ic calcium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/calcium
grep -ic scandium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/scandium
grep -ic titanium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/titanium
grep -ic vanadium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/vanadium
grep -ic chromium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/chromium
grep -ic manganese osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/manganese
grep -ic iron osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/iron
grep -ic cobalt osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/cobalt
grep -ic nickel osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/nickel
grep -ic copper osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/copper
grep -ic zinc osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/zinc
grep -ic gallium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/gallium
grep -ic germanium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/germanium
grep -ic arsenic osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/arsenic
grep -ic selenium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/selenium
grep -ic bromine osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/bromine
grep -ic krypton osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/krypton
grep -ic rubidium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/rubidium
grep -ic strontium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/strontium
grep -ic yttrium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/yttrium
grep -ic zirconium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/zirconium
grep -ic niobium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/niobium
grep -ic molybdenum osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/molybdenum
grep -ic technetium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/technetium
grep -ic ruthenium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/ruthenium
grep -ic rhodium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/rhodium
grep -ic palladium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/palladium
grep -ic silver osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/silver
grep -ic cadmium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/cadmium
grep -ic indium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/indium
grep -ic tin osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/tin
grep -ic antimony osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/antimony
grep -ic tellurium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/tellurium
grep -ic iodine osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/iodine
grep -ic xenon osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/xenon
grep -ic cesium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/cesium
grep -ic barium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/barium
grep -ic lanthanum osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/lanthanum
grep -ic cerium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/cerium
grep -ic praseodymium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/praseodymium
grep -ic neodymium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/neodymium
grep -ic promethium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/promethium
grep -ic samarium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/samarium
grep -ic europium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/europium
grep -ic gadolinium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/gadolinium
grep -ic terbium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/terbium
grep -ic dysprosium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/dysprosium
grep -ic holmium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/holmium
grep -ic erbium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/erbium
grep -ic thulium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/thulium
grep -ic ytterbium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/ytterbium
grep -ic lutetium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/lutetium
grep -ic hafnium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/hafnium
grep -ic tantalum osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/tantalum
grep -ic tungsten osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/tungsten
grep -ic rhenium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/rhenium
grep -ic osmium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/osmium
grep -ic iridium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/iridium
grep -ic platinum osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/platinum
grep -ic gold osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/gold
grep -ic mercury osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/mercury
grep -ic thallium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/thallium
grep -ic lead osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/lead
grep -ic bismuth osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/bismuth
grep -ic polonium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/polonium
grep -ic astatine osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/astatine
grep -ic radon osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/radon
grep -ic francium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/francium
grep -ic radium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/radium
grep -ic actinium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/actinium
grep -ic thorium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/thorium
grep -ic protactinium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/protactinium
grep -ic uranium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/uranium
grep -ic neptunium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/neptunium
grep -ic plutonium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/plutonium
grep -ic americium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/americium
grep -ic curium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/curium
grep -ic berkelium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/berkelium
grep -ic californium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/californium
grep -ic einsteinium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/einsteinium
grep -ic fermium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/fermium
grep -ic mendelevium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/mendelevium
grep -ic nobelium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/nobelium
grep -ic lawrencium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/lawrencium
grep -ic rutherfordium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/rutherfordium
grep -ic dubnium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/dubnium
grep -ic seaborgium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/seaborgium
grep -ic bohrium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/bohrium
grep -ic hassium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/hassium
grep -ic meitnerium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/meitnerium
grep -ic darmstadtium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/darmstadtium
grep -ic roentgenium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/roentgenium
grep -ic copernicium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/copernicium
grep -ic nihonium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/nihonium
grep -ic flerovium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/flerovium
grep -ic moscovium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/moscovium
grep -ic livermorium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/livermorium
grep -ic tennessine osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/tennessine
grep -ic oganesson osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/oganesson
grep -ic ununennium osbooks-chemistry-bundle/modules/*/* > os-chem2e-elements/ununennium
