// Generated by SolidPython 1.1.1 on 2021-11-15 13:37:58
$fn = 50;


union() {
	cylinder(h = 0.5000000000, r = 1);
	rotate(a = [0, 0, 0]) {
		translate(v = [0, 0, 1.5000000000]) {
			cylinder(h = 0.5000000000, r = 1);
		}
	}
	rotate(a = [30, 0, 0]) {
		translate(v = [0, 0, 1.5000000000]) {
			cylinder(h = 0.5000000000, r = 1);
		}
	}
	rotate(a = [60, 0, 0]) {
		translate(v = [0, 0, 1.5000000000]) {
			cylinder(h = 0.5000000000, r = 1);
		}
	}
	rotate(a = [90, 0, 0]) {
		translate(v = [0, 0, 1.5000000000]) {
			cylinder(h = 0.5000000000, r = 1);
		}
	}
	rotate(a = [120, 0, 0]) {
		translate(v = [0, 0, 1.5000000000]) {
			cylinder(h = 0.5000000000, r = 1);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# SolidPython example code 
# Brygg Ullmer, Clemson University
# Written 2021-10-28

from solid import *        # load in SolidPython/SCAD support code

c1 = cylinder(r=1, h=.5)
outGeom = c1

c2 = translate([0,0,1.5])(c1)

numF = 5
rot  = 0; rotIncr = 30

for i in range(numF):
  c3 = rotate([rot,0,0])(c2)
  outGeom += c3; rot += rotIncr

radialSegments = 50; hdr = '$fn = %s;' % radialSegments # create a header for the export
scad_render_to_file(outGeom, 'exTg01.scad', file_header=hdr) # write the .scad file

### end ###

 
 
************************************************/
