// Generated by SolidPython 1.1.1 on 2021-11-01 23:15:44
$fn = 25;


union() {
	color(alpha = 1.0000000000, c = [0.5000000000, 0.5000000000, 0.6000000000]) {
		translate(v = [2060.5000000000, -5421.0000000000, 0]) {
			cube(size = [234.0000000000, 325.0000000000, 7]);
		}
	}
	translate(v = [2221.8209000000, -5354.5993800000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2180.9465600000, -5311.7628850000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2145.4989400000, -5285.8165100000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2244.1933150000, -5370.9783400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.5975000000]) {
				import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2174.4141250000, -5171.4284700000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2141.8458750000, -5179.5948750000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2208.8476150000, -5146.5524500000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2163.0644750000, -5266.1533600000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2160.1769800000, -5287.9001500000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2108.1775000000, -5243.7320000000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2243.0664750000, -5363.1568900000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2250.6575650000, -5179.8386900000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2237.3078000000, -5223.8033900000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2224.5665650000, -5217.8742200000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2282.4780550000, -5298.0202600000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2168.6909400000, -5282.6698600000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2242.6321450000, -5177.8624300000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2096.3328750000, -5256.6851350000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2222.4222800000, -5263.4241400000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2164.3265800000, -5194.9066000000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2167.5852900000, -5243.6064200000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2162.0821300000, -5252.3855150000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2141.1843050000, -5276.7467350000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2216.4942800000, -5367.7353600000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2227.5263400000, -5238.4148050000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2181.2562850000, -5242.0293250000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2282.0201950000, -5339.1222950000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2249.9315800000, -5298.0918250000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2207.5668550000, -5269.3604600000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2258.1045500000, -5381.6572550000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2218.5252700000, -5286.5683000000, 0]) {
		translate(v = [0, 0, 3]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# SolidPython example code 
# Brygg Ullmer, Clemson University
# Written 2021-10-27

from solid import *        # load in SolidPython/SCAD support code
import csv
from mcmBolts import *

scPopCoordFn = 'sc-pop-coord.csv'; scPCF = open(scPopCoordFn, "r")
scpcReader   = csv.reader(scPCF, delimiter=",")

hlCities = ['Clemson', 'Greenville', 'Columbia', 'Charleston', 'Hartsville', 'Travelers Rest'] #highlight cities

#minMaxLatLong = [32.1632, 35.156486, -78.67792, -83.110782]
#minMaxLatLong = [32.0632, 35.256486, -78.77792, -83.010782]
#minMaxLatLong = [31.5, 35.8, -79, -84]
#minMaxLatLong = [31.5, 35.5, -79., -84.]
minMaxLatLong = [31.9, 35.5, -78.5, -83.5]

############### buildGroundPlane ###############

def buildGroundPlane(multiplier):
  global minMaxLatLong 
  minlat, maxlat, minlong, maxlong = minMaxLatLong 

  difflat  = abs(maxlat - minlat)
  difflong = abs(maxlong - minlong)

  difflat2  = difflat  * multiplier
  difflong2 = difflong * multiplier

  cx = (minlong + maxlong)/2 * multiplier 
  cy = (minlat + maxlat)/2 * multiplier 

  #print(difflat2, difflong2, cx - difflat2/2, cy)

  c1 = cube([difflat2, difflong2, 7])
  c2 = translate([cy-difflong2/2.5, cx-difflat2/1.5, 0])(c1)
  c3 = color([.5,.5,.6])(c2)
  return c3

############### map pop 2 bolt ###############

#boltPopHash  = boltPopHashY = {0: 'n0', 30000: 'n0', 75000: 'n4', 200000: 'n1_4'}
boltPopHash  = boltPopHashY = {0: 'n0', 20000: 'n0', 30000: 'n2', 75000: 'n4', 200000: 'n1_4'}

def mapPop2Bolt(popStr, boltObj, boltPopHash):
  global   boltSpec
  try:     pop = int(popStr)
  except:  return 1

  popThresh = boltPopHash.keys()
  idx = 0
  for testPop in popThresh:
    if pop > testPop: idx += 1
    else:             
      key = list(popThresh)[idx]
      boltSpec = boltPopHash[key]
      #print("bs1:", boltSpec)
      return boltObj.synthBoltNeutral(boltSpec)
  lpt = len(popThresh)
  if idx >=lpt: idx = lpt-1
  try:
    key = list(popThresh)[idx]
    boltSpec = boltPopHash[key]
    #print("bs2:", boltSpec)
    return boltObj.synthBoltNeutral(boltSpec)
  except: return -1

############### main ###############

multiplier = 65.

boltObj = mcmBolts()
outGeom = buildGroundPlane(multiplier)

minlat, maxlat, minlong, maxlong = [None, None, None, None]

for row in scpcReader:
  city, popStr, lat, long = row
  bolt1 = mapPop2Bolt(popStr, boltObj, boltPopHash)

  #if city=="Columbia": print(city, bolt1)
  if isinstance(bolt1, int): continue #ignore errors

  if city in hlCities and boltSpec == 'n0': bolt1 = mapPop2Bolt(30000, boltObj, boltPopHash)

  if boltSpec == 'n0': bolt2 = translate([0,0,3])(rotate([0,-90,0])(bolt1))
  else:                bolt2 = rotate([180,0,0])(bolt1)
  if boltSpec == 'n1_4': print(city)

  #if minlat == None or lat < minlat: minlat = lat
  #if maxlat == None or lat > maxlat: maxlat = lat

  #if minlong == None or long < minlong: minlong = long
  #if maxlong == None or long > maxlong: maxlong = long

  coord = [float(lat)*multiplier, float(long)*multiplier, 0]
  #print("coord:", coord, str(bolt))
  y2 = translate(coord)(bolt2)
  #print(city, y2)

  if outGeom == None:    outGeom = y2
  elif city in hlCities: break; outGeom += color([1,.5,0])(y2)
  else:                  outGeom += y2

radialSegments = 25; hdr = '$fn = %s;' % radialSegments # create a header for the export

#print(minlat, maxlat, minlong, maxlong)

scad_render_to_file(outGeom, 'scNodes8a.scad', file_header=hdr) # write the .scad file

### end ###

 
 
************************************************/
