// Generated by SolidPython 1.1.1 on 2021-10-27 23:54:47


union() {
	cube();
	translate(v = [1.5000000000, 0, 0]) {
		cube();
	}
	translate(v = [3, 0, 0]) {
		cylinder();
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# SolidPython example code 
# Brygg Ullmer, Clemson University

from solid import *        # load in SolidPython/SCAD support code

c1 = cube()
c2 = translate([1.5, 0, 0])(c1)
outGeom = c1 + c2

y1 = cylinder()
y2 = translate([3, 0, 0])(y1)
outGeom += y2

#print(scad_render(outGeom))
radialSegments = 25; hdr = '$fn = %s;' % radialSegments # create a header for the export
scad_render_to_file(outGeom, 'exSolid02.scad', hdr)    # write the .scad file

### end ###

 
 
************************************************/
