// Generated by SolidPython 1.1.1 on 2021-11-01 16:07:03
$fn = 25;


union() {
	translate(v = [341.8186000000, -823.7845200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.5302400000, -817.1942900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [330.0767600000, -813.2025400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.2605100000, -826.3043600000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.5252500000, -795.6043800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [329.5147500000, -796.8607500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.8227100000, -791.7773000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [332.7791500000, -810.1774400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [332.3349200000, -813.5231000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [324.3350000000, -806.7280000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.0871500000, -825.1010600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.2550100000, -796.8982600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [344.2012000000, -803.6620600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.2410100000, -802.7498800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [351.1504700000, -815.0800400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.6447600000, -812.7184400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.0203300000, -796.5942200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [322.5127500000, -808.7207900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.9111200000, -809.7575600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [332.9733200000, -799.2164000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.4746600000, -806.7086800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [332.6280200000, -808.0593100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [329.4129700000, -811.8071900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [340.9991200000, -825.8054400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.6963600000, -805.9099700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.5778900000, -806.4660500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [351.0800300000, -821.4034300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.1433200000, -815.0910500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.6256700000, -810.6708400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.4007000000, -827.9472700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.3115800000, -813.3182000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [327.7950600000, -799.3706900000, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [346.8627500000, -799.1741400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [351.1539800000, -818.6782700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.1489700000, -812.1856000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.2783400000, -800.9577000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [346.8306100000, -828.2500300000, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [344.7069200000, -818.7717000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.8052000000, -795.4525500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [351.1072800000, -811.8635800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.7306600000, -790.5571200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.7255500000, -809.6311100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.2753000000, -808.8571900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [329.6117100000, -804.7941400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.9051400000, -797.5152300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [350.3897900000, -818.2201900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.6927400000, -819.8427800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.0029400000, -798.7322100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.2092500000, -811.4072000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [344.1455300000, -793.7701500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.9977200000, -823.6661600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.3442500000, -824.0016400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.1764500000, -821.2582100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [348.2903100000, -825.7955200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.1527400000, -806.9964700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.0555300000, -819.6602000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [331.0443600000, -810.2213700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.6196300000, -808.1129200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.8027800000, -813.7972200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.9060800000, -805.6784000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [327.3751400000, -812.1776800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.9218900000, -803.1998300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [329.5145500000, -812.5864000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.8375000000, -797.7278600000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [326.5500000000, -799.4055600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.0064000000, -809.0917500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [350.2416700000, -810.2805600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.5333400000, -822.6459300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [326.8138900000, -811.8833300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [350.6150800000, -816.4906100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.3371200000, -811.1739500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.3077600000, -793.2345900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [328.5944400000, -812.3916700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.5805000000, -813.9136000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [329.8869900000, -800.1994800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.8098400000, -821.5703500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.7053000000, -809.1326300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.9664000000, -799.8022000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [349.1370000000, -820.9780000000, 0]) {
			translate(v = [0, 0, -1.5975000000]) {
				import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [341.7580200000, -821.5621100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [348.9680000000, -822.6744200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [328.7288000000, -810.9733300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [322.6351200000, -810.6686500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [332.2051100000, -804.5009400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [343.7561600000, -800.8423700000, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [346.0242200000, -807.1031000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [337.4188700000, -794.4889500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.7083300000, -814.3059900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [332.7333300000, -812.4722200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [321.6320000000, -807.5330000000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.8816700000, -822.1422500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.2758600000, -804.0239300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [327.2230600000, -802.5956600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [344.4172300000, -824.2547100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [350.5279500000, -820.5401300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.1025400000, -811.9655300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.1984700000, -826.5743700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.3888600000, -817.9762800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [332.2879700000, -797.1555100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.5458100000, -803.6393400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.7169300000, -812.7115300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.2987300000, -794.7825600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.2307500000, -817.9724200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [348.3736800000, -816.8421800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.5780900000, -805.5463300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [336.8784100000, -797.8322100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.6547300000, -797.4179400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.4449000000, -791.9286900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.8904400000, -800.3013400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.4900600000, -807.6157600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [351.5648600000, -822.1147300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.0827000000, -798.7154500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.3982900000, -794.4170400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.0071400000, -820.2677400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.8138900000, -812.3638900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.8718900000, -826.9742900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.6756900000, -814.1837500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.8638900000, -814.6222200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [329.8226300000, -809.3464100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [340.5575600000, -789.1609600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.6624000000, -825.7102100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [328.6177000000, -812.2350600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.6844300000, -821.4347900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [340.5260300000, -800.9882100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [336.6771600000, -802.2207800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.5619500000, -793.8982200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.8067500000, -823.0350700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [340.4646300000, -802.3492700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [331.6307100000, -800.3657600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [337.7472900000, -815.3629900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.4389500000, -802.4279100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [328.1621100000, -798.5203100000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.0444100000, -792.5415500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [337.5870100000, -788.0444800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.3428200000, -810.8343300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.1724200000, -816.8737600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.8466100000, -816.1574100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.4262900000, -791.6249300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.6519800000, -820.2918500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.6547200000, -827.5549200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [336.2112100000, -810.6009600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.1776600000, -819.3479400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.2280100000, -786.7792000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.5340200000, -811.0974400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.2854500000, -799.1534900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [331.8364000000, -811.6404200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.0254500000, -808.5928200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.0170800000, -817.5870300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.7219300000, -803.9661500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.9216600000, -795.9291700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [337.8611100000, -822.1972200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [345.5982300000, -800.6498400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.5082500000, -791.3412800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.4055600000, -813.2361100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [337.7662800000, -812.5016100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.4606300000, -824.6733400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.3694000000, -827.4062300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.0240300000, -827.0578400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [337.6421600000, -804.9776100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.3289300000, -822.4804100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.0628100000, -814.4997300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [323.8420500000, -806.9278000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.8324300000, -815.3235300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [327.8808800000, -802.2234600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [331.8721300000, -806.6725000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [348.6277800000, -821.1444400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.8218500000, -809.8906100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.7140300000, -816.5594900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [324.9193800000, -809.4943500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [331.0801700000, -803.0861100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.1665100000, -809.2881300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.1506800000, -810.1290400000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.7025700000, -808.3311500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.3792800000, -801.9096600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [348.7283600000, -829.6068700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.9723300000, -813.1841800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [340.1745100000, -817.7539800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.8353300000, -804.8049800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [326.8083300000, -812.4361100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.2813000000, -797.7310100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.6952200000, -794.3694800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.3470000000, -829.4820000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.0839600000, -813.7290700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [342.3555300000, -817.0368400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.3694400000, -822.5444400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [348.2828700000, -828.2779500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [330.9631900000, -808.1302100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [350.3078400000, -813.8960600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [344.5116100000, -798.8649400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.3521100000, -819.6537700000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.3426500000, -812.4985800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.9619600000, -826.8971000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [335.9457800000, -803.6056600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [330.2804500000, -801.7385200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.2819900000, -803.2100800000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [337.3391700000, -810.9330900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [330.3555600000, -812.2222200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.4388900000, -795.8666700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [341.0124100000, -799.3784500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [350.0392900000, -824.2717900000, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [336.9375700000, -818.5339200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.5565400000, -822.9407700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.7857000000, -799.8517400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [330.5759700000, -812.2129200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.2685500000, -816.2023500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.1388200000, -804.6171600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [328.3489300000, -810.2883900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [336.4941700000, -813.9952000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.6890200000, -830.3877800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [328.9736700000, -806.7922500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [338.8485600000, -817.2834100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [344.0249100000, -822.6779000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.3673000000, -820.8796800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.5139400000, -820.9270600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [339.9502400000, -810.8883600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.5157200000, -830.3988700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.5885700000, -831.1078200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [344.9548500000, -816.0598100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [330.3444400000, -808.4277800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [346.2057200000, -825.1100600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [333.9260800000, -814.1614600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [334.6744600000, -815.1362600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [343.8100800000, -811.0899000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [347.5786400000, -820.4465800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [326.4298300000, -808.1293200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [349.9466900000, -812.2446200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# SolidPython example code 
# Brygg Ullmer, Clemson University
# Written 2021-10-27

from solid import *        # load in SolidPython/SCAD support code
import csv
from mcmBolts import *

scPopCoordFn = 'sc-pop-coord.csv'; scPCF = open(scPopCoordFn, "r")
scpcReader   = csv.reader(scPCF, delimiter=",")

hlCities = ['Clemson', 'Greenville', 'Columbia', 'Charleston', 'Hartsville', 'Travelers Rest'] #highlight cities

############### map pop 2 bolt ###############

boltPopHash  = boltPopHashY = {0: 'n2', 50000: 'n4', 200000: 'n8', 500000: 'n1_4'}

def mapPop2Bolt(popStr, boltObj, boltPopHash):
  try:     pop = int(popStr)
  except:  return 1

  popThresh = boltPopHash.keys()
  idx = 0
  for testPop in popThresh:
    if pop > testPop: idx += 1
    else:             
      key = list(popThresh)[idx]
      boltSpec = boltPopHash[key]
      #print("bs1:", boltSpec)
      return boltObj.synthBoltNeutral(boltSpec)
  try:
    key = list(popThresh)[idx]
    boltSpec = boltPopHash[key]
    #print("bs2:", boltSpec)
    return boltObj.synthBoltNeutral(boltSpec)
  except: return -1

############### main ###############

boltObj = mcmBolts()
outGeom = None

for row in scpcReader:
  city, popStr, lat, long = row
  bolt = mapPop2Bolt(popStr, boltObj, boltPopHash)
  coord = [float(lat)*10, float(long)*10, 0]
  if isinstance(bolt, int): continue #not sure why, but could be throwing issues
  #print("coord:", coord, str(bolt))
  y2 = translate(coord)(bolt)
  #print(city, y2)

  if outGeom == None:    outGeom = y2
  elif city in hlCities: outGeom += color([1,.5,0])(y2)
  else:                  outGeom += y2

radialSegments = 25; hdr = '$fn = %s;' % radialSegments # create a header for the export
scad_render_to_file(outGeom, 'scNodes5.scad', file_header=hdr) # write the .scad file

### end ###

 
 
************************************************/
