// Generated by SolidPython 1.1.1 on 2021-11-01 16:05:32
$fn = 25;


union() {
	translate(v = [34.1818600000, -82.3784520000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5530240000, -81.7194290000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.0076760000, -81.3202540000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5260510000, -82.6304360000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4525250000, -79.5604380000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.9514750000, -79.6860750000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9822710000, -79.1777300000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.2779150000, -81.0177440000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.2334920000, -81.3523100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.4335000000, -80.6728000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5087150000, -82.5101060000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6255010000, -79.6898260000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.4201200000, -80.3662060000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2241010000, -80.2749880000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.1150470000, -81.5080040000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3644760000, -81.2718440000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5020330000, -79.6594220000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.2512750000, -80.8720790000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1911120000, -80.9757560000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.2973320000, -79.9216400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3474660000, -80.6708680000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.2628020000, -80.8059310000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.9412970000, -81.1807190000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.0999120000, -82.5805440000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2696360000, -80.5909970000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5577890000, -80.6466050000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.1080030000, -82.1403430000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6143320000, -81.5091050000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9625670000, -81.0670840000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7400700000, -82.7947270000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1311580000, -81.3318200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [32.7795060000, -79.9370690000, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [34.6862750000, -79.9174140000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.1153980000, -81.8678270000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7148970000, -81.2185600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7278340000, -80.0957700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [34.6830610000, -82.8250030000, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [34.4706920000, -81.8771700000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5805200000, -79.5452550000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.1107280000, -81.1863580000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8730660000, -79.0557120000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3725550000, -80.9631110000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4275300000, -80.8857190000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.9611710000, -80.4794140000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9905140000, -79.7515230000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.0389790000, -81.8220190000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2692740000, -81.9842780000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3002940000, -79.8732210000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3209250000, -81.1407200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.4145530000, -79.3770150000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3997720000, -82.3666160000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3344250000, -82.4001640000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9176450000, -82.1258210000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.8290310000, -82.5795520000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9152740000, -80.6996470000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8055530000, -81.9660200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.1044360000, -81.0221370000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1619630000, -80.8112920000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3802780000, -81.3797220000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4906080000, -80.5678400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.7375140000, -81.2177680000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3921890000, -80.3199830000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.9514550000, -81.2586400000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1837500000, -79.7727860000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.6550000000, -79.9405560000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7006400000, -80.9091750000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.0241670000, -81.0280560000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6533340000, -82.2645930000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.6813890000, -81.1883330000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.0615080000, -81.6490610000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8337120000, -81.1173950000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4307760000, -79.3234590000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.8594440000, -81.2391670000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9580500000, -81.3913600000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.9886990000, -80.0199480000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5809840000, -82.1570350000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5705300000, -80.9132630000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5966400000, -79.9802200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [34.9137000000, -82.0978000000, 0]) {
			translate(v = [0, 0, -1.5975000000]) {
				import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [34.1758020000, -82.1562110000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.8968000000, -82.2674420000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.8728800000, -81.0973330000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.2635120000, -81.0668650000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.2205110000, -80.4500940000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [34.3756160000, -80.0842370000, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [34.6024220000, -80.7103100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.7418870000, -79.4488950000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9708330000, -81.4305990000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.2733330000, -81.2472220000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.1632000000, -80.7533000000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2881670000, -82.2142250000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3275860000, -80.4023930000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.7223060000, -80.2595660000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.4417230000, -82.4254710000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.0527950000, -82.0540130000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1102540000, -81.1965530000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3198470000, -82.6574370000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3388860000, -81.7976280000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.2287970000, -79.7155510000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6545810000, -80.3639340000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2716930000, -81.2711530000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8298730000, -79.4782560000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8230750000, -81.7972420000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.8373680000, -81.6842180000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5578090000, -80.5546330000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.6878410000, -79.7832210000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8654730000, -79.7417940000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3444900000, -79.1928690000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1890440000, -80.0301340000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7490060000, -80.7615760000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.1564860000, -82.2114730000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5082700000, -79.8715450000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3398290000, -79.4417040000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5007140000, -82.0267740000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9813890000, -81.2363890000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7871890000, -82.6974290000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1675690000, -81.4183750000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7863890000, -81.4622220000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.9822630000, -80.9346410000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.0557560000, -78.9160960000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2662400000, -82.5710210000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.8617700000, -81.2235060000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9684430000, -82.1434790000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.0526030000, -80.0988210000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.6677160000, -80.2220780000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1561950000, -79.3898220000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7806750000, -82.3035070000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.0464630000, -80.2349270000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.1630710000, -80.0365760000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.7747290000, -81.5362990000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7438950000, -80.2427910000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.8162110000, -79.8520310000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2044410000, -79.2541550000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.7587010000, -78.8044480000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5342820000, -81.0834330000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4172420000, -81.6873760000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2846610000, -81.6157410000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2426290000, -79.1624930000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1651980000, -82.0291850000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7654720000, -82.7554920000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.6211210000, -81.0600960000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5177660000, -81.9347940000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8228010000, -78.6779200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4534020000, -81.1097440000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9285450000, -79.9153490000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.1836400000, -81.1640420000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5025450000, -80.8592820000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9017080000, -81.7587030000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7721930000, -80.3966150000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9921660000, -79.5929170000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.7861110000, -82.2197220000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.5598230000, -80.0649840000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4508250000, -79.1341280000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2405560000, -81.3236110000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.7766280000, -81.2501610000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6460630000, -82.4673340000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6369400000, -82.7406230000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9024030000, -82.7057840000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.7642160000, -80.4977610000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8328930000, -82.2480410000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3062810000, -81.4499730000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.3842050000, -80.6927800000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1832430000, -81.5323530000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.7880880000, -80.2223460000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.1872130000, -80.6672500000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.8627780000, -82.1144440000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6821850000, -80.9890610000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8714030000, -81.6559490000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.4919380000, -80.9494350000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.1080170000, -80.3086110000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3166510000, -80.9288130000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9150680000, -81.0129040000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3702570000, -80.8331150000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7379280000, -80.1909660000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.8728360000, -82.9606870000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5972330000, -81.3184180000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.0174510000, -81.7753980000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4835330000, -80.4804980000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.6808330000, -81.2436110000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9281300000, -79.7731010000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2695220000, -79.4369480000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7347000000, -82.9482000000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9083960000, -81.3729070000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.2355530000, -81.7036840000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7369440000, -82.2544440000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.8282870000, -82.8277950000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.0963190000, -80.8130210000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [35.0307840000, -81.3896060000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.4511610000, -79.8864940000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9352110000, -81.9653770000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5342650000, -81.2498580000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3961960000, -82.6897100000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.5945780000, -80.3605660000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.0280450000, -80.1738520000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9281990000, -80.3210080000, 0]) {
		translate(v = [0, 0, -1.0600000000]) {
			import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.7339170000, -81.0933090000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.0355560000, -81.2222220000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6438890000, -79.5866670000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.1012410000, -79.9378450000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [35.0039290000, -82.4271790000, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [33.6937570000, -81.8533920000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9556540000, -82.2940770000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8785700000, -79.9851740000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.0575970000, -81.2212920000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7268550000, -81.6202350000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4138820000, -80.4617160000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.8348930000, -81.0288390000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.6494170000, -81.3995200000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7689020000, -83.0387780000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.8973670000, -80.6792250000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.8848560000, -81.7283410000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.4024910000, -82.2677900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3367300000, -82.0879680000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9513940000, -82.0927060000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.9950240000, -81.0888360000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7515720000, -83.0398870000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6588570000, -83.1107820000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.4954850000, -81.6059810000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.0344440000, -80.8427780000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.6205720000, -82.5110060000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.3926080000, -81.4161460000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [33.4674460000, -81.5136260000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.3810080000, -81.1089900000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.7578640000, -82.0446580000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [32.6429830000, -80.8129320000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
	translate(v = [34.9946690000, -81.2244620000, 0]) {
		translate(v = [0, 0, -0.9200000000]) {
			import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# SolidPython example code 
# Brygg Ullmer, Clemson University
# Written 2021-10-27

from solid import *        # load in SolidPython/SCAD support code
import csv
from mcmBolts import *

scPopCoordFn = 'sc-pop-coord.csv'; scPCF = open(scPopCoordFn, "r")
scpcReader   = csv.reader(scPCF, delimiter=",")

hlCities = ['Clemson', 'Greenville', 'Columbia', 'Charleston', 'Hartsville', 'Travelers Rest'] #highlight cities

############### map pop 2 bolt ###############

boltPopHash  = boltPopHashY = {0: 'n2', 50000: 'n4', 200000: 'n8', 500000: 'n1_4'}

def mapPop2Bolt(popStr, boltObj, boltPopHash):
  try:     pop = int(popStr)
  except:  return 1

  popThresh = boltPopHash.keys()
  idx = 0
  for testPop in popThresh:
    if pop > testPop: idx += 1
    else:             
      key = list(popThresh)[idx]
      boltSpec = boltPopHash[key]
      #print("bs1:", boltSpec)
      return boltObj.synthBoltNeutral(boltSpec)
  try:
    key = list(popThresh)[idx]
    boltSpec = boltPopHash[key]
    #print("bs2:", boltSpec)
    return boltObj.synthBoltNeutral(boltSpec)
  except: return -1

############### main ###############

boltObj = mcmBolts()
outGeom = None

for row in scpcReader:
  city, popStr, lat, long = row
  bolt = mapPop2Bolt(popStr, boltObj, boltPopHash)
  coord = [float(lat), float(long), 0]
  if isinstance(bolt, int): continue #not sure why, but could be throwing issues
  #print("coord:", coord, str(bolt))
  y2 = translate(coord)(bolt)
  #print(city, y2)

  if outGeom == None:    outGeom = y2
  elif city in hlCities: outGeom += color([1,.5,0])(y2)
  else:                  outGeom += y2

radialSegments = 25; hdr = '$fn = %s;' % radialSegments # create a header for the export
scad_render_to_file(outGeom, 'scNodes5.scad', file_header=hdr) # write the .scad file

### end ###

 
 
************************************************/
