// Generated by SolidPython 1.1.1 on 2021-11-01 18:07:19
$fn = 25;


union() {
	color(alpha = 1.0000000000, c = [0.5000000000, 0.5000000000, 0.6000000000]) {
		translate(v = [2060.5000000000, -5421.0000000000, 0]) {
			cube(size = [234.0000000000, 325.0000000000, 7]);
		}
	}
	translate(v = [2221.8209000000, -5354.5993800000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2180.9465600000, -5311.7628850000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2145.4989400000, -5285.8165100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2244.1933150000, -5370.9783400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.5975000000]) {
				import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2174.4141250000, -5171.4284700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2141.8458750000, -5179.5948750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2208.8476150000, -5146.5524500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2163.0644750000, -5266.1533600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2160.1769800000, -5287.9001500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2108.1775000000, -5243.7320000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2243.0664750000, -5363.1568900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2250.6575650000, -5179.8386900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2237.3078000000, -5223.8033900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2224.5665650000, -5217.8742200000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2282.4780550000, -5298.0202600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2168.6909400000, -5282.6698600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2242.6321450000, -5177.8624300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2096.3328750000, -5256.6851350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2222.4222800000, -5263.4241400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2164.3265800000, -5194.9066000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2167.5852900000, -5243.6064200000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2162.0821300000, -5252.3855150000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2141.1843050000, -5276.7467350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2216.4942800000, -5367.7353600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2227.5263400000, -5238.4148050000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2181.2562850000, -5242.0293250000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2282.0201950000, -5339.1222950000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2249.9315800000, -5298.0918250000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2207.5668550000, -5269.3604600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2258.1045500000, -5381.6572550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2218.5252700000, -5286.5683000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [2130.6678900000, -5195.9094850000, 0]) {
			rotate(a = [180, 0, 0]) {
				translate(v = [0, 0, -1.5975000000]) {
					import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2254.6078750000, -5194.6319100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2282.5008700000, -5321.4087550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2256.4683050000, -5279.2064000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2257.3092100000, -5206.2250500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [2254.3989650000, -5383.6251950000, 0]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2240.5949800000, -5322.0160500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2247.7338000000, -5170.4415750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2282.1973200000, -5277.1132700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [2210.0260000000, -5267.1721700000, 0]) {
			rotate(a = [180, 0, 0]) {
				translate(v = [0, 0, -1.5975000000]) {
					import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2201.7492900000, -5138.6212800000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2169.2160750000, -5262.6022150000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2172.7894500000, -5257.5717350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2142.4761150000, -5231.1619100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2209.3834100000, -5183.8489950000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2277.5336350000, -5318.4312350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2227.5028100000, -5328.9780700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2229.5191100000, -5191.7593650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2165.8601250000, -5274.1468000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2236.9459450000, -5159.5059750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2235.9851800000, -5353.8300400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2231.7376250000, -5356.0106600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2269.6469250000, -5338.1783650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2263.8870150000, -5367.6708800000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2204.4928100000, -5245.4770550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2197.3609450000, -5327.7913000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2151.7883400000, -5266.4389050000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2220.5275950000, -5252.7339800000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2169.7180700000, -5289.6819300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2176.8895200000, -5236.9096000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2127.9384100000, -5279.1549200000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2170.4922850000, -5220.7988950000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2141.8445750000, -5281.8116000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2221.9437500000, -5185.2310900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.5975000000]) {
				import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2122.5750000000, -5196.1361400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2255.5416000000, -5259.0963750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2276.5708550000, -5266.8236400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2252.4667100000, -5347.1985450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2124.2902850000, -5277.2416450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2278.9980200000, -5307.1889650000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2199.1912800000, -5272.6306750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2173.0004400000, -5156.0248350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2135.8638600000, -5280.5458550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2207.2732500000, -5290.4384000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2144.2654350000, -5201.2966200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2247.7639600000, -5340.2072750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2247.0844500000, -5259.3620950000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2183.7816000000, -5198.7143000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [2269.3905000000, -5336.3570000000, 0]) {
			rotate(a = [180, 0, 0]) {
				translate(v = [0, 0, -1.5975000000]) {
					import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2221.4271300000, -5340.1537150000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2268.2920000000, -5347.3837300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2136.7372000000, -5271.3266450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2097.1282800000, -5269.3462250000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2159.3332150000, -5229.2561100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [2234.4150400000, -5205.4754050000, 0]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2249.1574300000, -5246.1701500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2193.2226550000, -5164.1781750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2273.1041450000, -5292.9889350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2162.7666450000, -5281.0694300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2090.6080000000, -5248.9645000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2228.7308550000, -5343.9246250000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2166.2930900000, -5226.1555450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2126.9498900000, -5216.8717900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2238.7119950000, -5357.6556150000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2278.4316750000, -5333.5108450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2217.1665100000, -5277.7759450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2230.7900550000, -5372.7334050000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2167.0275900000, -5316.8458200000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2159.8718050000, -5181.5108150000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2252.5477650000, -5223.6557100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2227.6600450000, -5282.6249450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2198.9417450000, -5166.0866400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2198.4998750000, -5316.8207300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2264.4289200000, -5309.4741700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2246.2575850000, -5236.0511450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2189.7096650000, -5185.9093650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2201.2557450000, -5183.2166100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2232.3918500000, -5147.5364850000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2222.2878600000, -5201.9587100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2258.6853900000, -5249.5024400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2285.1715900000, -5343.7457450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2178.0375500000, -5191.6504250000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2232.0888850000, -5163.7107600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2242.5464100000, -5331.7403100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2208.7902850000, -5280.3652850000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2261.1672850000, -5375.3328850000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2220.8919850000, -5292.1943750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2261.1152850000, -5295.0444300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2143.8470950000, -5260.7516650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2213.6241400000, -5129.5462400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2227.3056000000, -5367.1163650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2136.0150500000, -5279.5278900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2272.9487950000, -5339.3261350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2213.4191950000, -5206.4233650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2188.4015400000, -5214.4350700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2220.1526750000, -5160.3384300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2260.7438750000, -5349.7279550000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2213.0200950000, -5215.2702550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2155.5996150000, -5202.3774400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2195.3573850000, -5299.8594350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2258.3531750000, -5215.7814150000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2133.0537150000, -5190.3820150000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2223.2886650000, -5151.5200750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2194.3155650000, -5122.2891200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2179.7283300000, -5270.4231450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2172.1207300000, -5309.6794400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2228.5029650000, -5305.0231650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2225.7708850000, -5145.5620450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2220.7378700000, -5331.8970250000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2259.7556800000, -5379.1069800000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2185.3728650000, -5268.9062400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2178.6547900000, -5325.7616100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2140.6512400000, -5205.6200950000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.5975000000]) {
				import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2198.4820650000, -5114.0648000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2174.4711300000, -5272.1333600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2205.3554250000, -5194.4976850000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2156.9366000000, -5275.6627300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2177.6654250000, -5255.8533300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2268.6110200000, -5314.3156950000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2260.1925450000, -5225.7799750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2209.4907900000, -5173.5396050000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2196.0972150000, -5344.2819300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2246.3884950000, -5204.2239600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2174.3036250000, -5143.7183200000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2225.6361400000, -5286.0347150000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2195.4808200000, -5281.2604650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2251.9940950000, -5360.3767100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2251.4011000000, -5378.1404950000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2268.6561950000, -5375.8759600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2194.6740400000, -5232.3544650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2199.1380450000, -5346.1226650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2229.9082650000, -5294.2482450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2104.9733250000, -5245.0307000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2221.9107950000, -5299.6029450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2131.2257200000, -5214.4524900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2157.1688450000, -5243.3712500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2266.0805700000, -5337.4388600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2254.3420250000, -5264.2889650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2201.6411950000, -5307.6366850000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2111.9759700000, -5261.7132750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2152.0211050000, -5220.0597150000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2230.5823150000, -5260.3728450000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2269.4794200000, -5265.8387600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.5975000000]) {
				import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2169.0667050000, -5254.1524750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2257.9653200000, -5212.4127900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2266.7343400000, -5392.4446550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2183.8201450000, -5285.6971700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2211.1343150000, -5315.4008700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2176.4296450000, -5231.2323700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2124.2541450000, -5280.8347150000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2205.3284500000, -5185.2515650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2227.5189300000, -5163.4016200000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2257.7555000000, -5391.6330000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.8550000000]) {
				import(file = "bolts/97715A400_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2269.0457400000, -5289.2389550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2225.3109450000, -5310.7394600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2257.9013600000, -5346.5388600000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2263.8386550000, -5383.8066750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2151.2607350000, -5252.8463650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2277.0009600000, -5290.3243900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2239.3254650000, -5192.6221100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2270.7887150000, -5327.7495050000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.5975000000]) {
				import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2179.7272250000, -5281.2407700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2235.7527400000, -5374.8311500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2183.6475700000, -5223.4367900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2146.8229250000, -5211.3003800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2205.3329350000, -5220.8655200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2192.7046050000, -5271.0650850000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2147.3111400000, -5279.4444300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2251.8527850000, -5173.1333550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2216.5806650000, -5195.9599250000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [2275.2553850000, -5357.7666350000, 0]) {
			rotate(a = [0, -90, 0]) {
				translate(v = [0, 0, -1.4950000000]) {
					import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [2190.0942050000, -5320.4704800000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2207.1175100000, -5349.1150050000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2202.1070500000, -5199.0363100000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2148.7438050000, -5279.3839800000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2257.2455750000, -5305.3152750000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2171.9023300000, -5230.0115400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2134.2680450000, -5266.8745350000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2187.2121050000, -5290.9688000000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2259.9786300000, -5397.5205700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2138.3288550000, -5244.1496250000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2202.5156400000, -5312.3421650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2236.1619150000, -5347.4063500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2231.8874500000, -5335.7179200000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2271.8406100000, -5336.0258900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2209.6765600000, -5270.7743400000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2258.8521800000, -5397.5926550000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2252.8257050000, -5402.2008300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2242.2065250000, -5304.3887650000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2147.2388600000, -5254.7805700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2250.3371800000, -5363.2153900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2170.5195200000, -5292.0494900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2175.3839900000, -5298.3856900000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2234.7655200000, -5272.0843500000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2259.2611600000, -5332.9027700000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2121.7938950000, -5252.8405800000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [2274.6534850000, -5279.5900300000, 0]) {
		rotate(a = [0, -90, 0]) {
			translate(v = [0, 0, -1.4950000000]) {
				import(file = "bolts/90081A055_NO THREADS_Zinc-Plated Steel Screw Nails.stl", origin = [0, 0]);
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# SolidPython example code 
# Brygg Ullmer, Clemson University
# Written 2021-10-27

from solid import *        # load in SolidPython/SCAD support code
import csv
from mcmBolts import *

scPopCoordFn = 'sc-pop-coord.csv'; scPCF = open(scPopCoordFn, "r")
scpcReader   = csv.reader(scPCF, delimiter=",")

hlCities = ['Clemson', 'Greenville', 'Columbia', 'Charleston', 'Hartsville', 'Travelers Rest'] #highlight cities

#minMaxLatLong = [32.1632, 35.156486, -78.67792, -83.110782]
#minMaxLatLong = [32.0632, 35.256486, -78.77792, -83.010782]
#minMaxLatLong = [31.5, 35.8, -79, -84]
#minMaxLatLong = [31.5, 35.5, -79., -84.]
minMaxLatLong = [31.9, 35.5, -78.5, -83.5]

############### buildGroundPlane ###############

def buildGroundPlane(multiplier):
  global minMaxLatLong 
  minlat, maxlat, minlong, maxlong = minMaxLatLong 

  difflat  = abs(maxlat - minlat)
  difflong = abs(maxlong - minlong)

  difflat2  = difflat  * multiplier
  difflong2 = difflong * multiplier

  cx = (minlong + maxlong)/2 * multiplier 
  cy = (minlat + maxlat)/2 * multiplier 

  print(difflat2, difflong2, cx - difflat2/2, cy)

  c1 = cube([difflat2, difflong2, 7])
  c2 = translate([cy-difflong2/2.5, cx-difflat2/1.5, 0])(c1)
  c3 = color([.5,.5,.6])(c2)
  return c3

############### map pop 2 bolt ###############

#boltPopHash  = boltPopHashY = {0: 'n0', 30000: 'n0', 75000: 'n4', 200000: 'n1_4'}
boltPopHash  = boltPopHashY = {0: 'n0', 20000: 'n0', 30000: 'n2', 75000: 'n4', 200000: 'n1_4'}

def mapPop2Bolt(popStr, boltObj, boltPopHash):
  global   boltSpec
  try:     pop = int(popStr)
  except:  return 1

  popThresh = boltPopHash.keys()
  idx = 0
  for testPop in popThresh:
    if pop > testPop: idx += 1
    else:             
      key = list(popThresh)[idx]
      boltSpec = boltPopHash[key]
      #print("bs1:", boltSpec)
      return boltObj.synthBoltNeutral(boltSpec)
  lpt = len(popThresh)
  if idx >=lpt: idx = lpt-1
  try:
    key = list(popThresh)[idx]
    boltSpec = boltPopHash[key]
    #print("bs2:", boltSpec)
    return boltObj.synthBoltNeutral(boltSpec)
  except: return -1

############### main ###############

multiplier = 65.

boltObj = mcmBolts()
outGeom = buildGroundPlane(multiplier)

minlat, maxlat, minlong, maxlong = [None, None, None, None]

for row in scpcReader:
  city, popStr, lat, long = row
  bolt1 = mapPop2Bolt(popStr, boltObj, boltPopHash)

  #if city=="Columbia": print(city, bolt1)
  if isinstance(bolt1, int): continue #ignore errors


  if boltSpec == 'n0': bolt2 = rotate([0,-90,0])(bolt1)
  else:                bolt2 = rotate([180,0,0])(bolt1)

  #if minlat == None or lat < minlat: minlat = lat
  #if maxlat == None or lat > maxlat: maxlat = lat

  #if minlong == None or long < minlong: minlong = long
  #if maxlong == None or long > maxlong: maxlong = long

  coord = [float(lat)*multiplier, float(long)*multiplier, 0]
  #print("coord:", coord, str(bolt))
  y2 = translate(coord)(bolt2)
  #print(city, y2)

  if outGeom == None:    outGeom = y2
  elif city in hlCities: outGeom += color([1,.5,0])(y2)
  else:                  outGeom += y2

radialSegments = 25; hdr = '$fn = %s;' % radialSegments # create a header for the export

#print(minlat, maxlat, minlong, maxlong)

scad_render_to_file(outGeom, 'scNodes7.scad', file_header=hdr) # write the .scad file

### end ###

 
 
************************************************/
