// Generated by SolidPython 1.1.1 on 2021-11-01 16:15:00
$fn = 25;


union() {
	translate(v = [1025.4558000000, -2471.3535600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1006.5907200000, -2451.5828700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [990.2302800000, -2439.6076200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1035.7815300000, -2478.9130800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1003.5757500000, -2386.8131400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [988.5442500000, -2390.5822500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1019.4681300000, -2375.3319000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [998.3374500000, -2430.5323200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [997.0047600000, -2440.5693000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [973.0050000000, -2420.1840000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1035.2614500000, -2475.3031800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1038.7650300000, -2390.6947800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1032.6036000000, -2410.9861800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1026.7230300000, -2408.2496400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1053.4514100000, -2445.2401200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1000.9342800000, -2438.1553200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1035.0609900000, -2389.7826600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [967.5382500000, -2426.1623700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1025.7333600000, -2429.2726800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [998.9199600000, -2397.6492000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1000.4239800000, -2420.1260400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [997.8840600000, -2424.1779300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [988.2389100000, -2435.4215700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1022.9973600000, -2477.4163200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1028.0890800000, -2417.7299100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1006.7336700000, -2419.3981500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1053.2400900000, -2464.2102900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1038.4299600000, -2445.2731500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1018.8770100000, -2432.0125200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.2021000000, -2483.8418100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1023.9347400000, -2439.9546000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [983.3851800000, -2398.1120700000, 0]) {
			rotate(a = [180, 0, 0]) {
				translate(v = [0, 0, -1.0600000000]) {
					import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [1040.5882500000, -2397.5224200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1053.4619400000, -2456.0348100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1041.4469100000, -2436.5568000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1041.8350200000, -2402.8731000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [1040.4918300000, -2484.7500900000, 0]) {
			rotate(a = [180, 0, 0]) {
				translate(v = [0, 0, -0.9200000000]) {
					import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [1034.1207600000, -2456.3151000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1037.4156000000, -2386.3576500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1053.3218400000, -2435.5907400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1016.1919800000, -2371.6713600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1001.1766500000, -2428.8933300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1002.8259000000, -2426.5715700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [988.8351300000, -2414.3824200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1019.7154200000, -2392.5456900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1051.1693700000, -2454.6605700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1028.0782200000, -2459.5283400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1029.0088200000, -2396.1966300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [999.6277500000, -2434.2216000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1032.4365900000, -2381.3104500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1031.9931600000, -2470.9984800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1030.0327500000, -2472.0049200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1047.5293500000, -2463.7746300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1044.8709300000, -2477.3865600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1017.4582200000, -2420.9894100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1014.1665900000, -2458.9806000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [993.1330800000, -2430.6641100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1024.8588900000, -2424.3387600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1001.4083400000, -2441.3916600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1004.7182400000, -2417.0352000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [982.1254200000, -2436.5330400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1001.7656700000, -2409.5994900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [988.5436500000, -2437.7592000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1025.5125000000, -2393.1835800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [979.6500000000, -2398.2166800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1041.0192000000, -2427.2752500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1050.7250100000, -2430.8416800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1039.6000200000, -2467.9377900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [980.4416700000, -2435.6499900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1051.8452400000, -2449.4718300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1015.0113600000, -2433.5218500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1002.9232800000, -2379.7037700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [985.7833200000, -2437.1750100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1018.7415000000, -2441.7408000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [989.6609700000, -2400.5984400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1037.4295200000, -2464.7110500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1037.1159000000, -2427.3978900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1007.8992000000, -2399.4066000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [1047.4110000000, -2462.9340000000, 0]) {
			rotate(a = [180, 0, 0]) {
				translate(v = [0, 0, -1.5975000000]) {
					import(file = "bolts/97715A176_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [1025.2740600000, -2464.6863300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1046.9040000000, -2468.0232600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [986.1864000000, -2432.9199900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [967.9053600000, -2432.0059500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [996.6153300000, -2413.5028200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [1031.2684800000, -2402.5271100000, 0]) {
			rotate(a = [180, 0, 0]) {
				translate(v = [0, 0, -0.9200000000]) {
					import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [1038.0726600000, -2421.3093000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1012.2566100000, -2383.4668500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1049.1249900000, -2442.9179700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [998.1999900000, -2437.4166600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [964.8960000000, -2422.5990000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1028.6450100000, -2466.4267500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [999.8275800000, -2412.0717900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [981.6691800000, -2407.7869800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1033.2516900000, -2472.7641300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1051.5838500000, -2461.6203900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1023.3076200000, -2435.8965900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1029.5954100000, -2479.7231100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1000.1665800000, -2453.9288400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [996.8639100000, -2391.4665300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1039.6374300000, -2410.9180200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1028.1507900000, -2438.1345900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1014.8961900000, -2384.3476800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1014.6922500000, -2453.9172600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1045.1210400000, -2450.5265400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1036.7342700000, -2416.6389900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1010.6352300000, -2393.4966300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1015.9641900000, -2392.2538200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1030.3347000000, -2375.7860700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1025.6713200000, -2400.9040200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.4701800000, -2422.8472800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1054.6945800000, -2466.3441900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1005.2481000000, -2396.1463500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1030.1948700000, -2383.2511200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1035.0214200000, -2460.8032200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1019.4416700000, -2437.0916700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1043.6156700000, -2480.9228700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1025.0270700000, -2442.5512500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1043.5916700000, -2443.8666600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [989.4678900000, -2428.0392300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1021.6726800000, -2367.4828800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1027.9872000000, -2477.1306300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [985.8531000000, -2436.7051800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1049.0532900000, -2464.3043700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1021.5780900000, -2402.9646300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1010.0314800000, -2406.6623400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1024.6858500000, -2381.6946600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1043.4202500000, -2469.1052100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1021.3938900000, -2407.0478100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [994.8921300000, -2401.0972800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1013.2418700000, -2446.0889700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.3168500000, -2407.2837300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [984.4863300000, -2395.5609300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1026.1332300000, -2377.6246500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1012.7610300000, -2364.1334400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1006.0284600000, -2432.5029900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1002.5172600000, -2450.6212800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1028.5398300000, -2448.4722300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1027.2788700000, -2374.8747900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1024.9559400000, -2460.8755500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.9641600000, -2482.6647600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1008.6336300000, -2431.8028800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1005.5329800000, -2458.0438200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1014.6840300000, -2360.3376000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1003.6020600000, -2433.2923200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1017.8563500000, -2397.4604700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [995.5092000000, -2434.9212600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1005.0763500000, -2425.7784600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1047.0512400000, -2452.7610900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1043.1657900000, -2411.8984500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1019.7649800000, -2387.7875100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1013.5833300000, -2466.5916600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1036.7946900000, -2401.9495200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1003.5247500000, -2374.0238400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1027.2166800000, -2439.7083300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1013.2988400000, -2437.5048300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1039.3818900000, -2474.0200200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1039.1082000000, -2482.2186900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1047.0720900000, -2481.1735200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1012.9264800000, -2414.9328300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1014.9867900000, -2467.4412300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1029.1884300000, -2443.4991900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [971.5261500000, -2420.7834000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1025.4972900000, -2445.9705900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [983.6426400000, -2406.6703800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [995.6163900000, -2420.0175000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1045.8833400000, -2463.4333200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1040.4655500000, -2429.6718300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1016.1420900000, -2449.6784700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [974.7581400000, -2428.4830500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [993.2405100000, -2409.2583300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1029.4995300000, -2427.8643900000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1047.4520400000, -2430.3871200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1001.1077100000, -2424.9934500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.1378400000, -2405.7289800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1046.1850800000, -2488.8206100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1007.9169900000, -2439.5525400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1020.5235300000, -2453.2619400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1004.5059900000, -2414.4149400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [980.4249900000, -2437.3083300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1017.8439000000, -2393.1930300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1028.0856600000, -2383.1084400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.0410000000, -2488.4460000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1047.2518800000, -2441.1872100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1027.0665900000, -2451.1105200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.1083200000, -2467.6333200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1044.8486100000, -2484.8338500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [992.8895700000, -2424.3906300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1050.9235200000, -2441.6881800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1033.5348300000, -2396.5948200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1048.0563300000, -2458.9613100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1006.0279500000, -2437.4957400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1031.8858800000, -2480.6913000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1007.8373400000, -2410.8169800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [990.8413500000, -2405.2155600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1017.8459700000, -2409.6302400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -1.0600000000]) {
				import(file = "bolts/97715A464_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1012.0175100000, -2432.7992700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [991.0666800000, -2436.6666600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1039.3166700000, -2387.6000100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1023.0372300000, -2398.1353500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	color(alpha = 1.0000000000, c = [1, 0.5000000000, 0]) {
		translate(v = [1050.1178700000, -2472.8153700000, 0]) {
			rotate(a = [180, 0, 0]) {
				translate(v = [0, 0, -0.9200000000]) {
					import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
				}
			}
		}
	}
	translate(v = [1010.8127100000, -2455.6017600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1018.6696200000, -2468.8223100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1016.3571000000, -2399.5552200000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [991.7279100000, -2436.6387600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1041.8056500000, -2448.6070500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1002.4164600000, -2413.8514800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [985.0467900000, -2430.8651700000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1009.4825100000, -2441.9856000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1043.0670600000, -2491.1633400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [986.9210100000, -2420.3767500000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1016.5456800000, -2451.8502300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1032.0747300000, -2468.0337000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1030.1019000000, -2462.6390400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1048.5418200000, -2462.7811800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1019.8507200000, -2432.6650800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.5471600000, -2491.1966100000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1039.7657100000, -2493.3234600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1034.8645500000, -2448.1794300000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [991.0333200000, -2425.2833400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1038.6171600000, -2475.3301800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1001.7782400000, -2442.4843800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1004.0233800000, -2445.4087800000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1031.4302400000, -2433.2697000000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1042.7359200000, -2461.3397400000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [979.2894900000, -2424.3879600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
	translate(v = [1049.8400700000, -2436.7338600000, 0]) {
		rotate(a = [180, 0, 0]) {
			translate(v = [0, 0, -0.9200000000]) {
				import(file = "bolts/97715A423_NO THREADS_Brass Button Head Hex Drive Screws.stl", origin = [0, 0]);
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# SolidPython example code 
# Brygg Ullmer, Clemson University
# Written 2021-10-27

from solid import *        # load in SolidPython/SCAD support code
import csv
from mcmBolts import *

scPopCoordFn = 'sc-pop-coord.csv'; scPCF = open(scPopCoordFn, "r")
scpcReader   = csv.reader(scPCF, delimiter=",")

hlCities = ['Clemson', 'Greenville', 'Columbia', 'Charleston', 'Hartsville', 'Travelers Rest'] #highlight cities

############### map pop 2 bolt ###############

boltPopHash  = boltPopHashY = {0: 'n2', 50000: 'n4', 200000: 'n8', 500000: 'n1_4'}

def mapPop2Bolt(popStr, boltObj, boltPopHash):
  try:     pop = int(popStr)
  except:  return 1

  popThresh = boltPopHash.keys()
  idx = 0
  for testPop in popThresh:
    if pop > testPop: idx += 1
    else:             
      key = list(popThresh)[idx]
      boltSpec = boltPopHash[key]
      #print("bs1:", boltSpec)
      return boltObj.synthBoltNeutral(boltSpec)
  try:
    key = list(popThresh)[idx]
    boltSpec = boltPopHash[key]
    #print("bs2:", boltSpec)
    return boltObj.synthBoltNeutral(boltSpec)
  except: return -1

############### main ###############

boltObj = mcmBolts()
outGeom = None

for row in scpcReader:
  city, popStr, lat, long = row
  bolt1 = mapPop2Bolt(popStr, boltObj, boltPopHash)
  if isinstance(bolt1, int): continue #ignore errors

  bolt2 = rotate([180,0,0])(bolt1)
  coord = [float(lat)*30., float(long)*30., 0]
  #print("coord:", coord, str(bolt))
  y2 = translate(coord)(bolt2)
  #print(city, y2)

  if outGeom == None:    outGeom = y2
  elif city in hlCities: outGeom += color([1,.5,0])(y2)
  else:                  outGeom += y2

radialSegments = 25; hdr = '$fn = %s;' % radialSegments # create a header for the export
scad_render_to_file(outGeom, 'scNodes5.scad', file_header=hdr) # write the .scad file

### end ###

 
 
************************************************/
